# F4 BlueSCSI
:toc: macro

`F4 BlueSCSI`, ported by https://github.com/androda[androda], is a fork of `BlueSCSI` which targets the STM32F401 and STM32F411 microcontrollers.

toc::[]

### Lineage
F4 BlueSCSI, BlueSCSI, and ArdSCSino are hardware that reproduces SCSI devices (hard disks) with an STM32 Microcontroller.

`BlueSCSI` was created by https://github.com/erichelgeson[erichelgeson]

`ArdSCSino-stm32` was created by https://github.com/ztto/ArdSCSino-stm32[ztto], and is the STM32 version of `ArdSCSino`

`ArdSCSino` was created by https://twitter.com/h_koma2[Tambo (TNB Seisakusho)]


## Discussion
Join us in #bluescsi on https://discord.gg/GKcvtgU7P9[Discord].


## Compatibility and Performance
https://github.com/androda/F4_BlueSCSI/wiki/System-Compatibility-and-Performance[Compatibility and Performance]


## Assembly
Assembly instructions are generally found on my separate site, here: https://androda.work/kit-assembly/
These aren't really assembly instructions either, mostly pictures of the assembled design with tips on which way things should be facing.

## Usage
https://github.com/erichelgeson/BlueSCSI/wiki/Usage[Usage] is intended to be the same as the parent project and will be kept in sync until the blue pill module's flash is all used.  Then F4 will start to diverge.


### Termination
Termination enable / disable is handled differently per board style.  See the instructions for each PCB design.


## Troubleshooting
(to be completed, currently similar to the parent repo - but there are no jumpers on these dev modules.)
https://github.com/erichelgeson/BlueSCSI/wiki/Troubleshooting


## Hardware Versions
Generally speaking, hardware versions follow a naming scheme.

Variant.Maker.Style.Version

For example: {F4.TbA.D.V1}

This is an F4 model from Tech by Androda, D is for Desktop and V1 means first revision.


## Development (Advanced, annoying to set up)
(to be completed)


## Notes

### Building the Code
- Build experience is unfortunately complex due to Maple's STM32F4 compatibility issues

### Making Gerbers for JLCPCB
https://support.jlcpcb.com/article/44-how-to-export-kicad-pcb-to-gerber-files

BlueSCSI(TM) - Eric Helgeson - All rights reserved. - Used with permission