# F4 BlueSCSI
:toc: macro

`F4 BlueSCSI`, ported by https://github.com/androda[androda], is a fork of `BlueSCSI` which targets the STM32F401 and STM32F411 microcontrollers.

toc::[]

### Lineage
F4 BlueSCSI, BlueSCSI, and ArdSCSino are hardware that reproduces SCSI devices (hard disks) with an STM32 Microcontroller.

`BlueSCSI` was created by https://github.com/erichelgeson[erichelgeson]

`ArdSCSino-stm32` was created by https://github.com/ztto/ArdSCSino-stm32[ztto], and is the STM32 version of `ArdSCSino`

`ArdSCSino` was created by https://twitter.com/h_koma2[Tambo (TNB Seisakusho)]


## Discussion
Join us in #bluescsi on https://discord.gg/GKcvtgU7P9[Discord] or open an issue on this repo.


## Compatibility
If your computer is not listed below - it may be compatible but there is no guarantee it will work. This device is designed and tested to work with many different Macs, PowerPC included.  In terms of goals, the greatest compatibility possible is the long term ideal (Macs, PCs, DEC computers, etc).

### Tested Compatible
(to be completed)

* LC II, LC III

* Mac IIci

* Quadra 700

* PowerMac 9600

* Beige G3


## Performance
(to be completed)


## Assembly
(to be completed)

## Usage
https://github.com/erichelgeson/BlueSCSI/wiki/Usage[Usage] is intended to be the same as the parent project and will be kept in sync until the blue pill module's flash is all used.  Then F4 will start to diverge.


### Termination
Termination enable / disable is handled differently per board style.  See the instructions for each PCB design.


## Troubleshooting
(to be completed)


## Hardware Versions
(to be completed)


## Development (Advanced, annoying to set up)
(to be completed)


## Notes

### Building the Code
- Build experience is unfortunately complex due to Maple's STM32F4 compatibility issues

### Making Gerbers for JLCPCB
https://support.jlcpcb.com/article/44-how-to-export-kicad-pcb-to-gerber-files

BlueSCSI(TM) - Eric Helgeson - All rights reserved. - Used with permission