M48
; DRILL file {KiCad (6.0.2)} date Fri Jul  1 05:11:35 2022
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2022-07-01T05:11:35-06:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.2)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.1260
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.1378
%
G90
G05
T1
X3.2774Y-4.1044
X3.6117Y-2.6911
T2
X4.9526Y-2.7224
T0
M30
